[tool.poetry]
name = "didactic-disco"
version = "0.1.1-alpha.15"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [{include = "disco"}]

[tool.poetry.dependencies]
python = "3.9"
ampel-plots = {version = "^0.8.0-alpha.0", source = "pypi"}
ampel-ztf = {version = "^0.8.0-alpha.2", source = "pypi"}
sncosmo = "^2.5.0"
iminuit = "^2.8.0"
numpy = "^1"
scipy = "^1.4"
beautifulsoup4 = "^4.10.0"
backoff = "^1.11.1"
requests = "^2.26.0"
astropy = "^4.3.1"
pymage = {url = "https://github.com/MickaelRigault/pymage/archive/v1.0.tar.gz#sha256=11e99c4ea06b76ca7fb5b42d1d35d64139a4fa6f7f163a2f0f9cc3ea0b3c55eb"}
# pymage has an undeclared dependency on pandas
pandas = "^1.3.3"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"
types-requests = "^2.25.9"
types-pytz = "^2021.1.2"

[tool.conda-lock]
channels = ["conda-forge"]

[tool.conda-lock.dependencies]
python-confluent-kafka = "1.5"
matplotlib-base = "3.*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
