name: ci

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
  pypi:
    runs-on: ubuntu-latest
    needs: [test, mypy]
    if: ${{ github.event_name == 'push' && ( contains(github.ref, '/tags/v') || contains(github.ref, 'refs/heads/main') ) }}



    steps:
    - name: Get commit range
      uses: actions/github-script@v3
      with:
        github-token: ${{ github.token }}
        script: 
          console.log(github)
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    # Check if the _last_ commit bumped the version
    - name: Check for version bump
      id: check
      run: |
        poetry_version() { awk '/^\s*$/{f=0};f{if ($1=="version") {gsub(/"/, "", $3); print($3)}};/\[tool\.poetry\]/{f=1}'; }
        echo "::set-output name=previous::$(git show HEAD^:pyproject.toml | poetry_version)"
        echo "::set-output name=current::$(git show HEAD:pyproject.toml | poetry_version)"
    - name: Dump ref
      run: echo ${{github.ref}}