name: ci

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  
  pypi:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && ( contains(github.ref, '/tags/v') || contains(github.ref, 'refs/heads/main') ) }}


    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install toml@3.0.0
    - name: Get commit range
      id: payload
      uses: actions/github-script@v4
      with:
        github-token: ${{ github.token }}
        debug: true
        script: |
          const toml = require('toml')
          async function getVersion(ref) {
            response = await github.repos.getContent({
              repo: context.repo.repo,
              owner: context.repo.owner,
              path: 'pyproject.toml',
              ref: ref
            });
            return toml.parse(Buffer.from(response.data.content, 'base64').toString())
              .tool
              .poetry
              .version;
          }

          before = await getVersion(context.payload.before);
          after = await getVersion(context.payload.after);

          tag = `v${after}`

          return {
            tag,
            bumped: before !== after,
            tagged: context.payload.ref === `refs/tags/${tag}`,
            is_main: context.payload.ref === `refs/heads/${context.payload.repository.default_branch}`
          }
    - name: Dump ref
      run: echo ${{ steps.payload.outputs.result }}
    - uses: actions/checkout@v2
  