name: ci

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  
  pypi:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && ( contains(github.ref, '/tags/v') || contains(github.ref, 'refs/heads/main') ) }}


    steps:
    - name: Get commit range
      id: commits
      uses: actions/github-script@v3
      with:
        github-token: ${{ github.token }}
        script: |
          console.log(context.payload.commits);
          return context.payload.commits.length+1
    - uses: actions/checkout@v2
      with:
        fetch-depth: ${{ steps.commits.outputs.result }}
    # Check if one of commits in context bumped the version
    - name: Check for version bump
      id: check
      run: |
        echo Checking last $((${{ steps.commits.outputs.result }}-1)) commits
        poetry_version() { awk '/^\s*$/{f=0};f{if ($1=="version") {gsub(/"/, "", $3); print($3)}};/\[tool\.poetry\]/{f=1}'; }
        echo "::set-output name=previous::$(git show HEAD~$((${{ steps.commits.outputs.result }}-1)):pyproject.toml | poetry_version)"
        echo "::set-output name=current::$(git show HEAD:pyproject.toml | poetry_version)"
    - name: Dump ref
      run: echo ${{ steps.check.outputs.previous }}->${{ steps.check.outputs.current }}